---
#vpn all-in-on playbook
#include radius server, with web ui
#include  pptp/l2tp/ikev1/ikev2/cisco any connect
#see group_vars/vpn.yml.example for configuration options

- hosts: all

  roles:
    - common
    - webserver
    - db
    - auth
    - role: radius-admin
      djra_host: '127.0.0.1'
      djra_port: 9001
    - role: ftao.nginx-reverse-proxy
      nginx_site_root: '/opt/djra/data/'
      nginx_site_name: 'radius-admin'
      nginx_site_server_name: 'default'
      nginx_site_port: "{{ djra_nginx_port | default(9002) }}"
      nginx_site_upstream_host: "127.0.0.1"
      nginx_site_upstream_port: 9001

    - pptp

    - role: ppp-radiusclient
      device_type: pptp

    - strongswan
    - l2tp
    - role: ppp-radiusclient
      device_type: l2tp

#    - openvpn
    - nat
    - role: ocserv
