---
#vpn all-in-on playbook
#include radius server, with web ui
#include  pptp/l2tp/ikev1/ikev2/cisco any connect
#see group_vars/vpn.yml.example for configuration options

- hosts: all

  roles:
    - common
    - webserver
    - db
    - auth
    - radius-admin

    - pptp

    - role: ppp-radiusclient
      device_type: pptp

    - strongswan
    - l2tp
    - role: ppp-radiusclient
      device_type: l2tp

#    - openvpn
    - nat
    - role: ocserv
